### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by nyckmaia** [simlmx/pyvst#2]
I'm trying to run yout `simple_host.py`, but I got this error message below:

```
 C:/Users/nyck/AppData/Local/Programs/Python/Python39/python.exe c:/Users/nyck/Desktop/pyvst/examples/simple_host.py
Traceback (most recent call last):
  File "c:\Users\nyck\Desktop\pyvst\examples\simple_host.py", line 2, in <module>
    from pyvst import SimpleHost
  File "C:\Users\nyck\AppData\Local\Programs\Python\Python39\lib\site-packages\pyvst\__init__.py", line 1, in <module>
    from .vstplugin import VstPlugin
  File "C:\Users\nyck\AppData\Local\Programs\Python\Python39\lib\site-packages\pyvst\vstplugin.py", line 8, in <module>
    from wurlitzer import pipes
  File "C:\Users\nyck\AppData\Local\Programs\Python\Python39\lib\site-packages\wurlitzer.py", line 39, in <module>
    libc = ctypes.CDLL(None)
  File "C:\Users\nyck\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable
```

- Windows 10 x64
- Python 3.9

**Comment by simlmx** [comment]
It's probably simply the library `wurlitzer`, that is being used to capture the stdout/stderr that causes issues: it's not compatible with Windows (interestingly enough the author of that library opened a PR to support windows... 9 hours ago! https://github.com/minrk/wurlitzer/pull/63).

I'm going to try remove the dependency or at least make it optional. Stay tuned!

**Comment by simlmx** [comment]
So I removed `wurlitzer` (#3) *but* I didn't manage to get the example to run: I get a segfault somewhere.
I used a random open source VST that I compiled inside a Docker (to run on Linux).
I might try with different VSTs because this used to work but it's likely that there is a bug somewhere in my code.

I don't have access to a Windows machine so I'd be glad if you told me what you see on Windows!

**Comment by nyckmaia** [comment]
You can close this issue.
Now, lets continue in #4 , ok?
